CrowdCont/urls.py
from django.contrib import admin
from django.urls import path,include

# from shopkeeper import views as shop
# from customer import views as custom

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('shopkeeper/',include('shopkeeper.urls')),
    path('customer/',include('customer.urls')),
]

cs299/finale/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('customer/', include('customer.urls')),
    path('shopkeeper/', include('shopkeeper.urls'))
]

home/urls.py
from django.urls import path,include
from . import views

app_name='home'

urlpatterns = [
    path('',views.index,name='index'),
]

shopkeeper/urls.py
from django.urls import path,include
from . import views

app_name='shopkeeper'

urlpatterns=[
    path('',views.index, name='shopkeeper'),
    path('register/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('logout/',views.userLogout,name='logout'), 
    path('profile/',views.profile,name="profile"),
    path('settings/',views.settings, name='settings'),   
]

cs229/shopkeeper/models.py
from calendar import EPOCH
from django.db import models
import datetime

# Create your models here.


class ShopData(models.Model):
    name = models.CharField(max_length=122)
    phone = models.CharField(max_length=122)
    email = models.CharField(max_length=122)
    Opentime = models.TimeField()
    closetime = models.TimeField()
    date = models.DateTimeField(default=datetime.datetime.now(), blank=True)

cs299/shopkeeper/models.py
from calendar import EPOCH
from django.db import models
import datetime

# Create your models here.


class ShopData(models.Model):
    name = models.CharField(max_length=122)
    phone = models.CharField(max_length=122)
    email = models.CharField(max_length=122)
    Opentime = models.TimeField()
    closetime = models.TimeField()
    date = models.DateTimeField(default=datetime.datetime.now(), blank=True)

    def __str__(self):
        return self.name 
    

shopkeeper/models.py
from django.db import models
from django.contrib.auth.models import User


class Shopkeeper(models.Model):
    user = models.OneToOneField(User, default=None, null=True, on_delete=models.CASCADE)
    shop_name = models.CharField(max_length=256,blank=False,default="")
    shop_bio = models.TextField(blank=False,default="")
    type = models.CharField(max_length=256,blank=False)
    is_customer = models.BooleanField(default=False,editable=False)
    capacity = models.IntegerField(null=True)
    opening_time = models.TimeField(null=True)
    closing_time = models.TimeField(null=True)
    
    def __str__(self):
        return self.user.first_name    

shopkeeper/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Shopkeeper

class shopkeeperForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model=User
        fields=['first_name','last_name','username','email','password']

SHOP_CHOICES = (
    ('A','A'),
    ('B','B'),
    ('C','C')
)
# class shopkeeperAddForm(forms.ModelForm):
#     type=forms.CharField(widget=forms.Select(choices=SHOP_CHOICES))
#     class Meta():
#         model=Shopkeeper
#         fields=['type']

class shop_settings(forms.ModelForm):
    type=forms.CharField(widget=forms.Select(choices=SHOP_CHOICES))
    opening_time = forms.TimeField(widget=forms.TextInput(attrs={'type': 'time'}) )
    closing_time = forms.TimeField(widget=forms.TextInput(attrs={'type': 'time'}) )
    class Meta():
        model=Shopkeeper
        fields=['shop_name','type','capacity','opening_time','closing_time','shop_bio']    

cs229/shopkeeper/views.py
from django.shortcuts import render
from datetime import datetime
from shopkeeper.models import ShopData

# Create your views here.


def register(request):
    if request.method == "POST":
        name = request.POST.get('name')
        phone = request.POST.get('number')
        email = request.POST.get('email')
        Opentime = request.POST.get('opentime')
        closetime = request.POST.get('closetime')
        ShopInfo = ShopData(name=name, phone=phone, email=email,
                            Opentime=Opentime, closetime=closetime, date=datetime.today())
        ShopInfo.save()
    return render(request, 'shopkeeper/register.html')

cs299/shopkeeper/views.py
from django.shortcuts import render
from datetime import datetime
from shopkeeper.models import ShopData
from django.contrib import messages

# Create your views here.


def register(request):
    if request.method == "POST":
        name = request.POST['name']
        phone = request.POST['number']
        email = request.POST['email']
        Opentime = request.POST['opentime']
        closetime = request.POST['closetime']
        ShopInfo = ShopData(name=name, phone=phone, email=email,
                            Opentime=Opentime, closetime=closetime, date=datetime.today())
        ShopInfo.save()
        messages.success(request, 'Profile has been reigstered')
    return render(request, 'shopkeeper/register.html')

shopkeeper/views.py
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.contrib import messages
from django.contrib.auth import authenticate,logout
from django.contrib.auth import login as auth_login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from .forms import shop_settings, shopkeeperForm
from .models import Shopkeeper


########### Home/Index Page #########################################

@login_required(login_url='login/')
def index(request):
    if not user_check(request):
        return render(request,'shopkeeper/401.html',status=401)
    return render(request, 'shopkeeper/index.html')

############ Profile Page ##################################

@login_required(login_url='login/')
def profile(request):
    if not user_check(request):
        return render(request,'shopkeeper/401.html',status=401)
    return render(request, 'shopkeeper/profile.html')

########### Settings Page #####################################

@login_required(login_url='login/')
def settings(request):
    if not user_check(request):
        return render(request,'shopkeeper/401.html',status=401)  
    profile=request.user.shopkeeper
    if request.method == 'POST':
        form = shop_settings(request.POST,instance=profile)
        if form.is_valid:
            form.save()
    else:
        form=shop_settings(instance=profile)
    return render(request, 'shopkeeper/settings.html',{'form':form})


########### Register Page #####################################

def register(request):
    if request.method == 'POST':
        form = shopkeeperForm(request.POST) 
        if form.is_valid() :
            add_user=form.save(commit=False)
            add_user.set_password(add_user.password)
            add_user.save()
            Shopkeeper.objects.create(user=add_user)

            # print(Shopkeeper.objects.filter(user=add_user).values())
            # username = form.cleaned_data.get('username')

            messages.success(request, f'Your account has been created! You are now able to log in')
            return redirect('shopkeeper:login')
    else:
        form = shopkeeperForm()
    return render(request, 'shopkeeper/register.html', {'form': form})

################ Login Page ###################################

def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        temp_user = authenticate(request, username=username, password=password)
        
        if temp_user is not None:
            form = auth_login(request,temp_user)
            messages.success(request, f' welcome {username} !!')
            return redirect('shopkeeper:shopkeeper')
        else:
            messages.info(request, f'Account Does Not Exist Please Register')
    form = AuthenticationForm()
    return render(request, 'shopkeeper/login.html', {'form':form})

################ Logout ##############################

@login_required
def userLogout(request):
    logout(request)
    return redirect('home:index')

################ Shopkeeper Check ####################    

def user_check(request):
    if hasattr(request.user,'shopkeeper') :
        return True
    return False

shopkeeper/templates/shopkeeper/401.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>404 Error - SB Admin</title>
    <link href="{% static 'shopkeeper/css/styles.css' %}" rel="stylesheet" type="text/css" />
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
</head>

<body>
    <div id="layoutError">
        <div id="layoutError_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-6">
                            <div class="text-center mt-4">
                                <h1 class="display-1">401</h1>
                                <p class="lead">Unauthorized</p>
                                <p>Access to this resource is denied.</p>
                                <a href="{% url 'home:index' %}">
                                    <i class="fas fa-arrow-left me-1"></i>
                                    Return to Home Page
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
        <div id="layoutError_footer">
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2022</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
    <script src="{% static 'shopkeeper/js/scripts.js' %}"></script>
</body>

</html>

shopkeeper/templates/shopkeeper/login-off.html
<!-- {% extends "home/index.html" %} -->
{% load crispy_forms_tags %}
{% block start %}

<div class="content-section col-md-8 col-md-offset-2">
  <center>
    <form method="POST" style="border: 1px solid black; margin: 4%; padding:10%; border-radius:1%;">
      {% csrf_token %}
      <fieldset class="form-group">
        {{ form|crispy}}
      </fieldset>
      <center>
        <button style="background: black; font-size: 2rem; padding:1%;" class="btn btn-outline-info" type="submit"><span
            class="glyphicon glyphicon-log-in"></span> &nbsp; login</button>
      </center>
      <br />
      <sub style="text-align: left;"><a href="{% url 'shopkeeper/register' %}"
          style="text-decoration: none; color: blue; padding:2%; cursor:pointer; margin-right:2%;">don't have
          account,sign up</a></sub>
    </form>
  </center>
</div>
{% endblock start %}

shopkeeper/templates/shopkeeper/login.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Login - ShopKeeper</title>
    <link href="{% static 'shopkeeper/css/styles.css' %}" rel="stylesheet" type="text/css" />
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
</head>

<body class="bg-primary">
    <div id="layoutAuthentication">
        <div id="layoutAuthentication_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-5">
                            <div class="card shadow-lg border-0 rounded-lg mt-5">
                                <div class="card-header">
                                    <h3 class="text-center font-weight-light my-4">Login</h3>
                                </div>
                                <div class="card-body">
                                    <form method="POST">
                                        {% csrf_token %}
                                        {{form |crispy}}
                                        <div class="d-flex align-items-center justify-content-between mt-4 mb-0">
                                            <input type="Submit" class="btn btn-primary" value="Login">
                                            {% comment %} <input type="Submit" value="Login"> {% endcomment %}
                                        </div>
                                    </form>
                                </div>
                                <div class="card-footer text-center py-3">
                                    <div class="small"><a href="{% url 'shopkeeper:register' %}">Need an account? Sign
                                            up!</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
        <div id="layoutAuthentication_footer">
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2022</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
    <script src="{% static 'shopkeeper/js/scripts.js' %}"></script>
</body>

</html>

shopkeeper/templates/shopkeeper/password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Password Reset - SB Admin</title>
    <link href="{% static 'shopkeeper/css/styles.css' %}" rel="stylesheet" type="text/css" />
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
</head>

<body class="bg-primary">
    <div id="layoutAuthentication">
        <div id="layoutAuthentication_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-5">
                            <div class="card shadow-lg border-0 rounded-lg mt-5">
                                <div class="card-header">
                                    <h3 class="text-center font-weight-light my-4">Password Recovery</h3>
                                </div>
                                <div class="card-body">
                                    <div class="small mb-3 text-muted">Enter your email address and we will send you a
                                        link to reset your password.</div>
                                    <form>
                                        <div class="form-floating mb-3">
                                            <input class="form-control" id="inputEmail" type="email"
                                                placeholder="name@example.com" />
                                            <label for="inputEmail">Email address</label>
                                        </div>
                                        <div class="d-flex align-items-center justify-content-between mt-4 mb-0">
                                            <a class="small" href="login.html">Return to login</a>
                                            <a class="btn btn-primary" href="login.html">Reset Password</a>
                                        </div>
                                    </form>
                                </div>
                                <div class="card-footer text-center py-3">
                                    <div class="small"><a href="register.html">Need an account? Sign up!</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
        <div id="layoutAuthentication_footer">
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2022</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
    <script src="../js/scripts.js"></script>
</body>

</html>

shopkeeper/templates/shopkeeper/profile.html
{% extends 'shopkeeper/index.html' %}
{% block content%}
{% load crispy_forms_tags %}
{% load static %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link href="{% static 'shopkeeper/css/style.css' %}" rel="stylesheet" type="text/css" />
<!------ Include the above in your HEAD tag ---------->

<div class="container emp-profile">
    <form method="post">
        <div class="row">
            <div class="col-md-4">
                <div class="profile-img">
                    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS52y5aInsxSm31CvHOFHWujqUx_wWTS9iM6s7BAm21oEN_RiGoog"
                        alt="" />
                    <div class="file btn btn-lg btn-primary">
                        Change Photo
                        <input type="file" name="file" />
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="profile-head">
                    <h5>
                        {{user.shopkeeper.shop_name|upper}}
                    </h5>
                        <h6>
                            Shopping Mall Patna
                        </h6>
                    <p class="proile-rating">Average Customer Rating : <span>8/10</span></p>
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab"
                                aria-controls="home" aria-selected="true">About</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-2">
                <div class="btn"><a href="{% url 'shopkeeper:settings'%}">Edit Profile</a></div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="profile-work">
                    <p>WORK LINK</p>
                    <a href="">Website Link</a><br />
                    <a href="">Bootsnipp Profile</a><br />
                    <a href="">Bootply Profile</a>
                    <p>SKILLS</p>
                    <a href="">Web Designer</a><br />
                    <a href="">Web Developer</a><br />
                    <a href="">WordPress</a><br />
                    <a href="">WooCommerce</a><br />
                    <a href="">PHP, .Net</a><br />
                </div>
            </div>
            <div class="col-md-8">
                <div class="tab-content profile-tab" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <div class="row">
                            <div class="col-md-6">
                                <label>Shop Name</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{user.shopkeeper}}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Name</label>
                            </div>
                            <div class="col-md-6">
                                <p>Kshiti Ghelani</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Email</label>
                            </div>
                            <div class="col-md-6">
                                <p>kshitighelani@gmail.com</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Phone</label>
                            </div>
                            <div class="col-md-6">
                                <p>123 456 7890</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Profession</label>
                            </div>
                            <div class="col-md-6">
                                <p>Web Developer and Designer</p>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                        <div class="row">
                            <div class="col-md-6">
                                <label>Experience</label>
                            </div>
                            <div class="col-md-6">
                                <p>Expert</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Hourly Rate</label>
                            </div>
                            <div class="col-md-6">
                                <p>10$/hr</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Total Projects</label>
                            </div>
                            <div class="col-md-6">
                                <p>230</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>English Level</label>
                            </div>
                            <div class="col-md-6">
                                <p>Expert</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Availability</label>
                            </div>
                            <div class="col-md-6">
                                <p>6 months</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <label>Your Bio</label><br />
                                <p>Your detail description</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

shopkeeper/templates/shopkeeper/register-off.html
<!-- {% extends "index.html" %}  -->
{% load crispy_forms_tags %}
{% block start %}

<div class="content-section col-md-8 col-md-offset-2">
  <form method="POST" style="border: 1px solid black; margin: 4%; padding:10%; border-radius:1%;">
    {% csrf_token %}
    <fieldset class="form-group">
      {{ form|crispy}}
      {{ form2|crispy}}
    </fieldset>
    <center>
      <button style="background: black; padding:2%; font-size: 2rem; color:white;" class="btn btn-outline-info"
        type="submit"><span class="glyphicon glyphicon-check"></span> &nbsp; sign up</button>
    </center>
    <br />
    <sub><a href="{% url 'shopkeeper/login' %}"
        style="text-decoration: none; color: blue; padding:3%; cursor:pointer;">Already
        have an account ?</a></sub>
  </form>
</div>
{% endblock start %}

shopkeeper/templates/shopkeeper/register.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Register - ShopKeeper </title>
    <link href="{% static 'shopkeeper/css/styles.css' %}" rel="stylesheet" type="text/css" />
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
</head>

<body class="bg-primary">
    <div id="layoutAuthentication">
        <div id="layoutAuthentication_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-7">
                            <div class="card shadow-lg border-0 rounded-lg mt-5">
                                <div class="card-header">
                                    <h3 class="text-center font-weight-light my-4">Create Account</h3>
                                </div>
                                <div class="card-body">
                                    <form method="POST">
                                        {% csrf_token %}
                                        {{form|crispy|linebreaks}}
                                        <div class="d-flex align-items-center justify-content-between mt-4 mb-0">
                                            <input type="Submit" class="btn btn-primary" value="Login">
                                        </div>
                                    </form>
                                </div>
                                <div class="card-footer text-center py-3">
                                    <div class="small"><a href="{% url 'shopkeeper:login'%}">Have an account? Go to
                                            login</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
        <div id="layoutAuthentication_footer">
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2022</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
    <script src="{% static 'shopkeeper/js/scripts.js' %}"></script>
</body>

</html>