CrowdCont/urls.py
from django.contrib import admin
from django.urls import path,include

# from shopkeeper import views as shop
# from customer import views as custom

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('shopkeeper/',include('shopkeeper.urls')),
    path('customer/',include('customer.urls')),
]

cs299/finale/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('customer/', include('customer.urls')),
    path('shopkeeper/', include('shopkeeper.urls'))
]

customer/urls.py
from django.urls import path, include
from . import views

app_name = 'customer'
urlpatterns = [
    path('', views.index, name='customer'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.userLogout, name='logout'),
    path('query/', views.query, name='query'),
    # path('profile/',views.profile,name="profile"),
]

home/urls.py
from django.urls import path,include
from . import views

app_name='home'

urlpatterns = [
    path('',views.index,name='index'),
]

shopkeeper/urls.py
from django.urls import path,include
from . import views

app_name='shopkeeper'

urlpatterns=[
    path('',views.index, name='shopkeeper'),
    path('register/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('logout/',views.userLogout,name='logout'), 
    path('profile/',views.profile,name="profile"),
    path('settings/',views.settings, name='settings'),   
]

cs299/customer/models.py
from calendar import EPOCH
from django.db import models
import datetime

# Create your models here.


class CustomerData(models.Model):
    name = models.CharField(max_length=122)
    email = models.CharField(max_length=122)
    contact = models.CharField(max_length=122)
    password = models.CharField(max_length=122)
    # prefftime=models.TimeField()
    # bit=models.CharField(max_length=10)
    date = models.DateTimeField(default=datetime.datetime.now(), blank=True)

    def __str__(self):
        return self.name


class QueryList(models.Model):
    user=models.ForeignKey(CustomerData,default=None,on_delete=models.CASCADE);
    prefftime1 = models.TimeField()
    prefftime2 = models.TimeField()
    prefftime3 = models.TimeField()
    bit = models.CharField(max_length=10)

    # def __str__(self):
    #     return self.name

customer/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.
class Customer(models.Model):
    user = models.OneToOneField(User, default=None, null=True, on_delete=models.CASCADE)
    is_customer = models.BooleanField(default=True,editable=False)
    prefftime1 = models.TimeField(null=True)
    prefftime2 = models.TimeField(null=True)
    prefftime3 = models.TimeField(null=True)
    bit = models.CharField(max_length=10,null=True)

    # shop_list = models.CharField(max_length=100,null=True)

    def __str__(self):
        return self.user.first_name

customer/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Customer
from shopkeeper.models import Shopkeeper

class CustomerForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model=User
        fields=['first_name','last_name','username','email','password']

SHOP_CHOICES = (
    ('A','A'),
    ('B','B'),
    ('C','C')
)

# def lister(type):
ls=list()
for shops in Shopkeeper.objects.all():
    ls.append((shops.shop_name,shops.shop_name))
ls=tuple(ls)
# class shopkeeperAddForm(forms.ModelForm):
#     type=forms.CharField(widget=forms.Select(choices=SHOP_CHOICES))
#     class Meta():
#         model=Shopkeeper
#         fields=['type']


# check this function
class customer_settings(forms.ModelForm):
    # shop_list=forms.CheckboxSelectMultiple(choices=ls)
    # shop_list=forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,choices=ls)
    prefftime1 = forms.TimeField(widget=forms.TextInput(attrs={'type': 'time'}),label='Preferred Time 1')
    prefftime2 = forms.TimeField(widget=forms.TextInput(attrs={'type': 'time'}),label='Preferred Time 2' )
    prefftime3 = forms.TimeField(widget=forms.TextInput(attrs={'type': 'time'}),label='Preferred Time 3' )
    # shop_list = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,choices=ls)
    class Meta():
        model=Customer
        fields=['prefftime1','prefftime2','prefftime3']    

cs299/customer/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.utils.datastructures import MultiValueDictKeyError
from .models import CustomerData, QueryList
from shopkeeper.models import ShopData
from datetime import datetime
from django.contrib import messages

# Create your views here.


def register(request: HttpRequest):
    if request.method == "POST":
        name = request.POST['name']
        phone = request.POST['number']
        email = request.POST['email']
        password = request.POST['password']
        CustomerInfo = CustomerData(name=name, contact=phone, email=email,
                                    password=password, date=datetime.today())
        CustomerInfo.save()
        messages.success(request, 'Profile has been registered')

    return render(request, 'customer/register.html')

def profile(request):
    Shop_list = ShopData.objects.all()
    if request.method == "POST":
        preftime1 = request.POST['prefftime1']
        preftime2 = request.POST['prefftime2']
        preftime3 = request.POST['prefftime3']
        s = ""
        for shop in Shop_list:
            try:
                request.POST[shop.name]
                s += '1'
            except MultiValueDictKeyError:
                s += '0'
        CustomerQuery = QueryList(
            prefftime1=preftime1, prefftime2=preftime2, prefftime3=preftime3, bit=s)
        CustomerQuery.save()
        messages.success(request, 'Query has been sent!')
    return render(request, 'profile.html', {'Shop_list': Shop_list})


def CustomerLogin(request):
    if request.method == "POST":
        userName = request.POST.get('username')
        passWord = request.POST.get('password')
        User = CustomerData.objects.filter(name=userName, password=passWord)
        # print(User)
        if len(User) == 1:
            return redirect('profile')
            # check redirect yourself once
        else:
            messages.warning(request, 'Invalid Credentials!')
            return redirect('login')
    else:
        return render(request, 'customer/login.html')


# def CustomerLogout(request):
#     return redirect(request, 'home.html')

customer/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, logout
from django.contrib.auth import login as auth_login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomerForm,customer_settings
from .models import Customer
from shopkeeper.models import Shopkeeper
########### Home Page #########################################


@login_required(login_url='login/')
def index(request):
    if not user_check(request):
        return render(request,'shopkeeper/401.html',status=401)      
    return render(request, 'customer/index.html')

############ Profile Page ##################################


# @login_required(login_url='login/')
# def profile(request):

#     return render(request, 'customer/profile.html')

########### Query Page #####################################


@login_required(login_url='login/')
def query(request):
    Shop_list=Shopkeeper.objects.all()
    if not user_check(request):
        return render(request,'shopkeeper/401.html',status=401)      
    profile = request.user.customer
    if request.method == 'POST':
        form = customer_settings(request.POST, instance=profile)
        if form.is_valid:
            form.save()
    else:
        form = customer_settings(instance=profile)
    return render(request, 'customer/query.html', {'form': form})


########### Register Page #####################################

def register(request):
    if request.method == 'POST':
        form = CustomerForm(request.POST)
        if form.is_valid():
            add_user = form.save(commit=False)
            add_user.set_password(add_user.password)
            add_user.save()
            Customer.objects.create(user=add_user)

            # print(Shopkeeper.objects.filter(user=add_user).values())
            # username = form.cleaned_data.get('username')

            messages.success(
                request, 'Your account has been created! You are now able to log in')
            return redirect('customer:login')
    else:
        form = CustomerForm()
    return render(request, 'customer/register.html', {'form': form})

################ Login Page ###################################

def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        temp_user = authenticate(request, username=username, password=password)

        if temp_user is not None:
            form = auth_login(request, temp_user)
            messages.success(request, f' welcome {username} !!')
            return redirect('customer:customer')
        else:
            messages.info(request, f'Account Does Not Exist Please Register')
    form = AuthenticationForm()
    return render(request, 'customer/login.html', {'form': form})



################ Logout ##############################

@login_required
def userLogout(request):
    logout(request)
    return redirect('home:index')

################# User Check ########################

def user_check(request):
    if hasattr(request.user,'customer') :
        return True
    return False

customer/templates/customer/401.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>401 Error - SB Admin</title>
    <link href="{% static 'shopkeeper/css/styles.css' %}" rel="stylesheet" type="text/css" />
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
</head>

<body>
    <div id="layoutError">
        <div id="layoutError_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-6">
                            <div class="text-center mt-4">
                                <h1 class="display-1">401</h1>
                                <p class="lead">Unauthorized</p>
                                <p>Access to this resource is denied.</p>
                                <a href="{% url 'home:index' %}">
                                    <i class="fas fa-arrow-left me-1"></i>
                                    Return to Home Page
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
        <div id="layoutError_footer">
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2022</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
    <script src="{% static 'shopkeeper/js/scripts.js' %}"></script>
</body>

</html>

customer/templates/customer/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard - SB Admin</title>
    <link
      href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css"
      rel="stylesheet"
    />
    <link
      href="{% static 'customer/css/styles.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    <script
      src="https://use.fontawesome.com/releases/v6.1.0/js/all.js"
      crossorigin="anonymous"
    ></script>
  </head>

  <body class="sb-nav-fixed">
    {% csrf_token %}
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
      <!-- Navbar Brand-->
      <a class="navbar-brand ps-3" href="{% url 'home:index' %}">Home</a>
      <!-- Sidebar Toggle-->
      <button
        class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0"
        id="sidebarToggle"
        href="#!"
      >
        <i class="fas fa-bars"></i>
      </button>
      <!-- Navbar Search-->
      <form
        class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0"
      >
        <div class="input-group">
          <input
            class="form-control"
            type="text"
            placeholder="Search for..."
            aria-label="Search for..."
            aria-describedby="btnNavbarSearch"
          />
          <button class="btn btn-primary" id="btnNavbarSearch" type="button">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </form>
      <!-- Navbar-->
      <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            id="navbarDropdown"
            href="#"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
            ><i class="fas fa-user fa-fw"></i
          ></a>
          <ul
            class="dropdown-menu dropdown-menu-end"
            aria-labelledby="navbarDropdown"
          >
            <li>
              <a class="dropdown-item" href="{% url 'customer:query' %}"
                >Settings</a
              >
            </li>
            {% comment %} <li>
              <a class="dropdown-item" href="{% url 'customer:profile' %}"
                >Profile</a
              >
            </li> {% endcomment %}
            {% comment %}
            <li><a class="dropdown-item" href="#!">Activity Log</a></li>
            {% endcomment %}
            <li>
              <hr class="dropdown-divider" />
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'customer:logout' %}"
                >Logout</a
              >
            </li>
          </ul>
        </li>
      </ul>
    </nav>
    <div id="layoutSidenav">
      <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
          <div class="sb-sidenav-menu">
            <div class="nav">
              <div class="sb-sidenav-menu-heading">Core</div>
              <a class="nav-link" href="{% url 'customer:customer' %}">
                <div class="sb-nav-link-icon">
                  <i class="fas fa-tachometer-alt"></i>
                </div>
                Dashboard
              </a>
              <div class="sb-sidenav-menu-heading">Interface</div>
              <a
                class="nav-link collapsed"
                href="{% url 'customer:query' %}"
              >
                <div class="sb-nav-link-icon">
                  <i class="fas fa-book-open"></i>
                </div>
                Query
                <div class="sb-sidenav-collapse-arrow">
                  <i class="fas fa-angle-down"></i>
                </div>
              </a>
              {% comment %} <div
                class="collapse"
                id="collapsePages"
                aria-labelledby="headingTwo"
                data-bs-parent="#sidenavAccordion"
              > {% endcomment %}
                {% comment %} <nav
                  class="sb-sidenav-menu-nested nav accordion"
                  id="sidenavAccordionPages"
                >
                  <a
                    class="nav-link collapsed"
                    href="{% url 'customer:query' %}"
                    data-bs-toggle="collapse"
                    data-bs-target="#pagesCollapseAuth"
                    aria-expanded="false"
                    aria-controls="pagesCollapseAuth"
                  >
                    Authentication
                  </a>
                </div>
              </nav> {% endcomment %}
              <div class="sb-sidenav-menu-heading">Addons</div>
              <a class="nav-link" href="tables.html">
                <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                Tables
              </a>
            </div>
          </div>
          <div class="sb-sidenav-footer">
            <div class="small">Logged in as:</div>
            {{user}}
          </div>
        </nav>
      </div>
      <div id="layoutSidenav_content">
        {% block content %}
        <main>
          <div class="container-fluid px-4">
            <h1 class="mt-4">Dashboard</h1>
            <ol class="breadcrumb mb-4">
              <li class="breadcrumb-item active">Dashboard</li>
            </ol>
            <div class="row">
              <div class="col-xl-3 col-md-6">
                <div class="card bg-primary text-white mb-4">
                  <div class="card-body">Primary Card</div>
                  <div
                    class="card-footer d-flex align-items-center justify-content-between"
                  >
                    <a class="small text-white stretched-link" href="#"
                      >View Details</a
                    >
                    <div class="small text-white">
                      <i class="fas fa-angle-right"></i>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xl-3 col-md-6">
                <div class="card bg-warning text-white mb-4">
                  <div class="card-body">Warning Card</div>
                  <div
                    class="card-footer d-flex align-items-center justify-content-between"
                  >
                    <a class="small text-white stretched-link" href="#"
                      >View Details</a
                    >
                    <div class="small text-white">
                      <i class="fas fa-angle-right"></i>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xl-3 col-md-6">
                <div class="card bg-success text-white mb-4">
                  <div class="card-body">Success Card</div>
                  <div
                    class="card-footer d-flex align-items-center justify-content-between"
                  >
                    <a class="small text-white stretched-link" href="#"
                      >View Details</a
                    >
                    <div class="small text-white">
                      <i class="fas fa-angle-right"></i>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xl-3 col-md-6">
                <div class="card bg-danger text-white mb-4">
                  <div class="card-body">Danger Card</div>
                  <div
                    class="card-footer d-flex align-items-center justify-content-between"
                  >
                    <a class="small text-white stretched-link" href="#"
                      >View Details</a
                    >
                    <div class="small text-white">
                      <i class="fas fa-angle-right"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="card mb-4">
              <div class="card-header">
                <i class="fas fa-table me-1"></i>
                DataTable Example
              </div>
              <div class="card-body">
                <table id="datatablesSimple">
                  <thead>
                    <tr>
                      <th>Name</th>
                      <th>Position</th>
                      <th>Office</th>
                      <th>Age</th>
                      <th>Start date</th>
                      <th>Salary</th>
                    </tr>
                  </thead>
                  <tfoot>
                    <tr>
                      <th>Name</th>
                      <th>Position</th>
                      <th>Office</th>
                      <th>Age</th>
                      <th>Start date</th>
                      <th>Salary</th>
                    </tr>
                  </tfoot>
                  <tbody>
                    <tr>
                      <td>Tiger Nixon</td>
                      <td>System Architect</td>
                      <td>Edinburgh</td>
                      <td>61</td>
                      <td>2011/04/25</td>
                      <td>$320,800</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </main>
        {% endblock %}
        <footer class="py-4 bg-light mt-auto">
          <div class="container-fluid px-4">
            <div
              class="d-flex align-items-center justify-content-between small"
            >
              <div class="text-muted">Copyright &copy; Your Website 2022</div>
              <div>
                <a href="#">Privacy Policy</a>
                &middot;
                <a href="#">Terms &amp; Conditions</a>
              </div>
            </div>
          </div>
        </footer>
      </div>
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'customer/js/scripts.js' %}"></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"
      crossorigin="anonymous"
    ></script>
    <!-- <script src="assets/demo/chart-area-demo.js"></script> -->
    <!-- <script src="assets/demo/chart-bar-demo.js"></script> -->
    <script
      src="https://cdn.jsdelivr.net/npm/simple-datatables@latest"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'customer/js/datatables-simple-demo.js'%}"></script>
  </body>
</html>

customer/templates/customer/login.html
{% load static %} {% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Login - Customer</title>
    <link
      href="{% static 'customer/css/styles.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    <script
      src="https://use.fontawesome.com/releases/v6.1.0/js/all.js"
      crossorigin="anonymous"
    ></script>
  </head>

  <body class="bg-primary">
    <div id="layoutAuthentication">
      <div id="layoutAuthentication_content">
        <main>
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                  <div class="card-header">
                    <h3 class="text-center font-weight-light my-4">Login</h3>
                  </div>
                  <div class="card-body">
                    <form method="POST">
                      {% csrf_token %} {{form |crispy}}
                      <div
                        class="d-flex align-items-center justify-content-between mt-4 mb-0"
                      >
                        <input
                          type="Submit"
                          class="btn btn-primary"
                          value="Login"
                        />
                        <!-- <input type="Submit" value="Login"> -->
                      </div>
                    </form>
                  </div>
                  <div class="card-footer text-center py-3">
                    <div class="small">
                      <a href="{% url 'customer:register' %}"
                        >Need an account? Sign up!</a
                      >
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </main>
      </div>
      <div id="layoutAuthentication_footer">
        <footer class="py-4 bg-light mt-auto">
          <div class="container-fluid px-4">
            <div
              class="d-flex align-items-center justify-content-between small"
            >
              <div class="text-muted">Copyright &copy; Your Website 2022</div>
              <div>
                <a href="#">Privacy Policy</a>
                &middot;
                <a href="#">Terms &amp; Conditions</a>
              </div>
            </div>
          </div>
        </footer>
      </div>
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'customer/js/scripts.js' %}"></script>
  </body>
</html>

customer/templates/customer/register.html
{% load static %} {% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Register - Customer</title>
    <link
      href="{% static 'customer/css/styles.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    <script
      src="https://use.fontawesome.com/releases/v6.1.0/js/all.js"
      crossorigin="anonymous"
    ></script>
  </head>

  <body class="bg-primary">
    <div id="layoutAuthentication">
      <div id="layoutAuthentication_content">
        <main>
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-lg-7">
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                  <div class="card-header">
                    <h3 class="text-center font-weight-light my-4">
                      Create Account
                    </h3>
                  </div>
                  <div class="card-body">
                    <form method="POST">
                      {% csrf_token %} {{form|crispy}}
                      <div
                        class="d-flex align-items-center justify-content-between mt-4 mb-0"
                      >
                        <input
                          type="Submit"
                          class="btn btn-primary"
                          value="Login"
                        />
                      </div>
                    </form>
                  </div>
                  <div class="card-footer text-center py-3">
                    <div class="small">
                      <a href="{% url 'customer:login'%}"
                        >Have an account? Go to login</a
                      >
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </main>
      </div>
      <div id="layoutAuthentication_footer">
        <footer class="py-4 bg-light mt-auto">
          <div class="container-fluid px-4">
            <div
              class="d-flex align-items-center justify-content-between small"
            >
              <div class="text-muted">Copyright &copy; Your Website 2022</div>
              <div>
                <a href="#">Privacy Policy</a>
                &middot;
                <a href="#">Terms &amp; Conditions</a>
              </div>
            </div>
          </div>
        </footer>
      </div>
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'customer/js/scripts.js' %}"></script>
  </body>
</html>